import type { NewProjectDraft } from './types';

export function bumpSemVer(currentVersion: string, bumpType: 'patch' | 'minor' | 'major'): string {
  const clean = currentVersion.replace(/^v/i, '').trim();
  const parts = clean.split('.').map((p) => {
    const num = parseInt(p, 10);
    return isNaN(num) ? 0 : num;
  });

  while (parts.length < 3) {
    parts.push(0);
  }

  let [major, minor, patch] = parts;

  if (bumpType === 'major') {
    major += 1;
    minor = 0;
    patch = 0;
  } else if (bumpType === 'minor') {
    minor += 1;
    patch = 0;
  } else {
    patch += 1;
  }

  const prefix = currentVersion.startsWith('v') || currentVersion.startsWith('V') ? 'v' : '';
  return `${prefix}${major}.${minor}.${patch}`;
}

export interface ChangelogItem {
  type: 'feat' | 'fix' | 'refactor' | 'docs' | 'chore';
  description: string;
}

export function generateChangelogEntry(
  version: string,
  items: ChangelogItem[],
  date: string = new Date().toISOString().split('T')[0]!
): string {
  const vTag = version.startsWith('v') ? version : `v${version}`;
  const sections: Record<string, string[]> = {
    Features: [],
    'Bug Fixes': [],
    Refactoring: [],
    Documentation: [],
    Maintenance: [],
  };

  for (const item of items) {
    switch (item.type) {
      case 'feat':
        sections['Features']!.push(item.description);
        break;
      case 'fix':
        sections['Bug Fixes']!.push(item.description);
        break;
      case 'refactor':
        sections['Refactoring']!.push(item.description);
        break;
      case 'docs':
        sections['Documentation']!.push(item.description);
        break;
      default:
        sections['Maintenance']!.push(item.description);
        break;
    }
  }

  let entry = `## [${vTag}] - ${date}\n\n`;
  for (const [title, list] of Object.entries(sections)) {
    if (list.length > 0) {
      entry += `### ${title}\n`;
      for (const line of list) {
        entry += `- ${line}\n`;
      }
      entry += '\n';
    }
  }

  return entry.trim();
}

export function generateReleaseNotes(
  version: string,
  highlights: string,
  binaryArtifacts: string[] = ['AppImage', 'tar.gz']
): string {
  const vTag = version.startsWith('v') ? version : `v${version}`;
  return `# Release ${vTag}

${highlights}

## Automated Production Binaries
This release was built and verified automatically via GitHub Actions CI/CD.
Included binary artifacts:
${binaryArtifacts.map((a) => `- \`${a}\``).join('\n')}

---
*Generated by IRIS Agentic Operating System*
`.trim();
}

export function generateReleaseWorkflow(projectName: string): string {
  return `name: Release & Binary Builds

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-release:
    name: Build ${projectName} Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js & pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
        continue-on-error: true

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        continue-on-error: true

      - name: Build Production Artifacts
        run: |
          echo "Building binary release artifacts for ${projectName}..."
          mkdir -p dist/binaries
          tar -czf "dist/binaries/${projectName}-linux-x86_64.tar.gz" . || true

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/binaries/*
          draft: false
          prerelease: false
          generate_release_notes: true
`;
}

export function generateLicenseContent(license: string, authorName: string = 'IRIS User'): string {
  const year = new Date().getFullYear();
  if (license === 'MIT') {
    return `MIT License

Copyright (c) ${year} ${authorName}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`;
  }

  if (license === 'Apache-2.0') {
    return `Apache License\nVersion 2.0, January 2004\n\nCopyright ${year} ${authorName}`;
  }

  return '';
}

export function generateGitignore(template?: string): string {
  const extra = template === 'rust' ? '\n**/*.rs.bk\n' : template === 'python' ? '\n__pycache__/\n*.pyc\n' : '';
  return `# General
node_modules/
dist/
build/
target/
.DS_Store
*.log
.env
.env.local
*.local${extra}
`;
}

export function generateReadme(draft: NewProjectDraft): string {
  const topicsList = draft.topics && draft.topics.length > 0 ? `\n**Tags:** ${draft.topics.map((t) => `\`${t}\``).join(' ')}\n` : '';
  const website = draft.website ? `\n🌐 [Website / Documentation](${draft.website})\n` : '';

  return `# ${draft.name}

${draft.description || 'A modern project managed with IRIS Operating Environment.'}
${topicsList}${website}
## Architecture & Overview
This repository uses structured, autonomous versioning with automated CI/CD binary builds.

## Getting Started
\`\`\`bash
# Clone the repository
git clone https://github.com/your-org/${draft.name}.git

# Navigate into directory
cd ${draft.name}
\`\`\`

## Releases & Automated Builds
Every tagged release (\`v*\`) triggers an automated GitHub Actions pipeline that packages and uploads production binaries.

---
*Created with IRIS Agentic Operating System v0.2.0*
`;
}

export function generateProjectScaffolding(draft: NewProjectDraft): { path: string; content: string }[] {
  const files: { path: string; content: string }[] = [];

  // README.md
  files.push({
    path: 'README.md',
    content: generateReadme(draft),
  });

  // .gitignore
  files.push({
    path: '.gitignore',
    content: generateGitignore(draft.template),
  });

  // LICENSE
  if (draft.license && draft.license !== 'None') {
    files.push({
      path: 'LICENSE',
      content: generateLicenseContent(draft.license),
    });
  }

  // GitHub Actions workflow
  if (draft.setupActionsWorkflow !== false) {
    files.push({
      path: '.github/workflows/release.yml',
      content: generateReleaseWorkflow(draft.name),
    });
  }

  return files;
}
